/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray;

@interface _VMUDWARFAbbrevDecl : NSObject
{
    unsigned long long _tag;
    BOOL _hasChildren;
    NSArray *_attributes;
}

+ (id)abbrevDeclWithTag:(unsigned long long)arg1 withChildren:(BOOL)arg2 withAttributes:(id)arg3;
- (id)description;
- (void)dealloc;

@end

