/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCoding-Protocol.h"

@interface VMUAddressRange : NSObject <NSCoding>
{
    struct _VMURange _addressRange;
}

- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

