/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, VMUMachOHeader;

@interface VMUDyld : NSObject
{
    VMUMachOHeader *_dyldMachOHeader;
    NSArray *_machOHeaders;
}

+ (id)dyldWithMachOHeader:(id)arg1 memory:(id)arg2;
- (id)initWithMachOHeader:(id)arg1 memory:(id)arg2;
- (id)findMachOHeadersInMemory:(id)arg1;
- (id)name;
- (id)machOHeaders;
- (void)dealloc;

@end

