/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Symbolication/VMUAddressRange.h>

@interface VMURangeValue : VMUAddressRange
{
    long long _value;
}

+ (id)rangeValueWithRange:(struct _VMURange)arg1 value:(long long)arg2;
- (id)initWithRange:(struct _VMURange)arg1 value:(long long)arg2;
- (struct _VMURange)addressRange;
- (long long)value;
- (long long)compare:(id)arg1;
- (id)description;

@end

