/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Symbolication/VMUSymbolExtractor.h>

@interface VMUStabsExtractor : VMUSymbolExtractor
{
}

+ (id)stabsExtractorWithMachOHeader:(id)arg1;
- (id)initWithMachOHeader:(id)arg1;
- (void)readIndirectSymbolsFromMachOHeader:(id)arg1 section:(id)arg2 nsyms:(unsigned int)arg3 indirectSymbols:(id)arg4 nlist:(id)arg5 stringTable:(id)arg6;
- (void)readStabsFromMachOHeader:(id)arg1 nsyms:(unsigned int)arg2 nlist:(id)arg3 stringTable:(id)arg4;

@end

