/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Symbolication/VMUAddressRange.h>

@interface VMUAddressRange (Private)
- (void)setAddressRange:(struct _VMURange)arg1;
@end

