/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class VMUSymbolOwner;

@interface VMULinkedListEntry : NSObject
{
    VMULinkedListEntry *_prev;
    VMULinkedListEntry *_next;
    unsigned long long _size;
    VMUSymbolOwner *_symbolOwner;
}

+ (id)linkedListEntryWithSymbolOwner:(id)arg1;
- (id)initWithSymbolOwner:(id)arg1;
- (unsigned long long)size;
- (id)symbolOwner;
- (id)prev;
- (id)next;
- (void)setPrev:(id)arg1;
- (void)setNext:(id)arg1;
- (id)description;
- (void)dealloc;

@end

