/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Symbolication/VMUMemoryView_Swapped.h>

@interface VMUMemoryView_Swapped32 : VMUMemoryView_Swapped
{
}

+ (id)memoryViewWithAddressRange:(struct _VMURange)arg1 data:(char *)arg2 memory:(id)arg3;
- (BOOL)isCursorPointerAligned;
- (void)pointerAlignCursor;

@end

