/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface VMUMemory_Base : NSObject
{
}

- (id)viewForArchitecture:(id)arg1 addressRange:(struct _VMURange)arg2 data:(char *)arg3;
- (id)swappedViewForArchitecture:(id)arg1 addressRange:(struct _VMURange)arg2 data:(char *)arg3;

@end

