/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Symbolication/VMUMemory_Base.h>

#import "VMUMemory-Protocol.h"

@class NSDate, NSString, VMUArchitecture;

@interface VMUMemory_File : VMUMemory_Base <VMUMemory>
{
    char *_mappedAddress;
    unsigned long long _mappedSize;
    NSDate *_lastModifiedTimestamp;
    struct _VMURange _addressRange;
    struct _VMURange _fileRange;
    NSString *_path;
    VMUArchitecture *_architecture;
}

+ (id)headerWithPath:(id)arg1;
+ (id)memoryWithPath:(id)arg1;
+ (id)memoryWithPath:(id)arg1 fileRange:(struct _VMURange)arg2 mapToAddress:(unsigned long long)arg3 architecture:(id)arg4;
- (id)initWithPath:(id)arg1 fileRange:(struct _VMURange)arg2 mapToAddress:(unsigned long long)arg3 architecture:(id)arg4;
- (id)path;
- (id)lastModifiedTimestamp;
- (BOOL)map;
- (id)description;
- (void)dealloc;
- (void)finalize;
- (struct _VMURange)addressRange;
- (id)architecture;
- (BOOL)isContiguous;
- (id)memoryAtAddress:(unsigned long long)arg1 maxSize:(unsigned long long)arg2;
- (id)memoryFromSubRange:(struct _VMURange)arg1 mapToAddress:(unsigned long long)arg2 architecture:(id)arg3;
- (id)view;
- (id)swappedView;

@end

