/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Symbolication/VMUSection.h>

@interface VMUSection64 : VMUSection
{
    unsigned int _reserved3;
}

- (id)initWithMemory:(id)arg1;
- (BOOL)isSection64;

@end

