/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import <Symbolication/VMUSegmentLoadCommand.h>

@interface VMUSegment32LoadCommand : VMUSegmentLoadCommand
{
}

- (id)initWithMemory:(id)arg1;
- (BOOL)isSegment32;

@end

