/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@interface VMUSymbolOwnerCache : NSObject
{
}

+ (void)initialize;
+ (id)symbolOwnerForSignature:(id)arg1;
+ (void)addSymbolOwner:(id)arg1;
+ (void)removeSignature:(id)arg1;
+ (id)symbolOwners;
+ (void)shrinkCacheToSize:(unsigned long long)arg1;
+ (void)flush;
+ (unsigned long long)memoryLimit;
+ (void)setMemoryLimit:(unsigned long long)arg1;

@end

