/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface VMUSymbolExtractor : NSObject
{
    NSMutableArray *_symbols;
    NSMutableArray *_sourceInfos;
}

+ (unsigned int)extractSymbolOwnerFlagsFromHeader:(id)arg1;
+ (id)extractLazySymbolOwnerFromHeader:(id)arg1;
+ (id)extractSymbolOwnerFromHeader:(id)arg1;
+ (id)expandSourceInfos:(id)arg1 usingSymbols:(id)arg2;
- (id)init;
- (id)symbols;
- (id)sourceInfos;
- (void)dealloc;

@end

