/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface VMUTraceSymbol : NSObject
{
    unsigned long long address;
    NSString *name;
    NSString *library;
    NSString *filename;
    int lineNumber;
}

- (id)initWithPC:(unsigned long long)arg1 withSymbolicator:(id)arg2;
- (id)initWithCString:(char *)arg1 length:(long long)arg2 withLine:(int)arg3;
- (id)name;
- (id)library;
- (id)filename;
- (int)lineNumber;
- (void)writeToFile:(struct __sFILE *)arg1;
- (BOOL)readFromFile:(struct __sFILE *)arg1;

@end

