/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMutableArray;

@interface VMUVMRegionIdentifier : NSObject
{
    NSMutableArray *_regions;
}

- (id)initWithTask:(unsigned int)arg1;
- (void)dealloc;
- (id)regions;
- (id)descriptionForRange:(struct _VMURange)arg1;
- (id)descriptionForRange:(struct _VMURange)arg1 options:(unsigned long long)arg2;
- (id)descriptionForRegionTotalsWithOptions:(unsigned long long)arg1;

@end

